# Generated by Django 6.0.7 on 2026-07-22 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('item_code', models.CharField(help_text='e.g. deal-zinger-combo', max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('tag', models.CharField(blank=True, help_text='e.g. Bestseller Deal, Hot Deal, Family Saver', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RestaurantInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Delicious Food Stop', max_length=100)),
                ('tagline', models.CharField(default='Fast Food & Pulao', max_length=255)),
                ('phone', models.CharField(default='+92 333 9342567', max_length=20)),
                ('whatsapp_number', models.CharField(default='923339342567', max_length=20)),
                ('email', models.EmailField(default='info@deliciousfoodstop.pk', max_length=254)),
                ('address', models.CharField(default='Jamrud, Khyber District, Khyber Pakhtunkhwa, Pakistan', max_length=255)),
                ('google_maps_plus_code', models.CharField(default='292F+QRP Jamrud', max_length=50)),
                ('google_rating', models.DecimalField(decimal_places=1, default=4.4, max_digits=3)),
                ('google_reviews_count', models.IntegerField(default=39)),
                ('opening_hours_text', models.CharField(default='Monday – Sunday: 11:00 AM – 10:00 PM', max_length=100)),
                ('lunch_hours', models.CharField(default='11:00 AM – 4:00 PM', max_length=100)),
                ('dinner_hours', models.CharField(default='5:00 PM – 10:00 PM', max_length=100)),
                ('hero_description', models.TextField(default='Experience the finest fast food in Jamrud. From wood-fired pizzas and local shawarmas to aromatic chicken pulao, we cook every deal fresh with premium ingredients.')),
                ('about_established_year', models.IntegerField(default=2018)),
                ('about_history', models.TextField(default='Delicious Food Stop opened in Jamrud in 2018 to serve flavorful, high-quality fast food—from wood-fired pizzas and shawarmas to crispy zinger burgers and aromatic chicken pulao.')),
                ('about_history_p2', models.TextField(default='We source fresh local ingredients, dry-age our beef in-house, and bake pizza dough from scratch daily to make every bite memorable.')),
                ('about_quality_promise', models.TextField(default='All of our signature sauces and dips are prepared fresh by our chefs every single morning. We select fresh farm veggies and premium meats, bringing you gourmet quality at fast-food convenience. Drop by today and taste the difference!')),
            ],
            options={
                'verbose_name': 'Restaurant Information',
                'verbose_name_plural': 'Restaurant Information',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('reviewer_role', models.CharField(default='Regular Diner', max_length=100)),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('comment', models.TextField()),
                ('avatar_url', models.URLField(default='https://i.pravatar.cc/120?img=33', max_length=255)),
                ('is_approved', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['display_order', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(help_text='Image path e.g. static/images/burger.jpg', max_length=255)),
                ('tag', models.CharField(blank=True, help_text="e.g., Popular, Bestseller, Chef's Special, Spicy, Crispy", max_length=50)),
                ('item_code', models.CharField(help_text='Unique HTML data-id for shopping cart e.g. pizza-tikka', max_length=50, unique=True)),
                ('custom_style', models.CharField(blank=True, help_text='Inline CSS filters e.g. filter: hue-rotate(45deg);', max_length=255)),
                ('is_available', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='website.category')),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
