# Generated by Django 6.0.7 on 2026-07-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='image_file',
            field=models.FileField(blank=True, help_text='Or upload deal image file directly', null=True, upload_to='deals/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_file',
            field=models.FileField(blank=True, help_text='Or upload image file directly', null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='review',
            name='avatar_file',
            field=models.FileField(blank=True, help_text='Or upload avatar image file directly', null=True, upload_to='avatars/'),
        ),
    ]
