# Generated by Django 6.0.7 on 2026-07-23 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_dailyvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.FileField(blank=True, help_text='Category image file', null=True, upload_to='categories/'),
        ),
    ]
