# Generated by Django 6.0.7 on 2026-07-23 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_category_image_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantinfo',
            name='is_open',
            field=models.BooleanField(default=True, help_text='Switch between OPEN and CLOSED for online ordering'),
        ),
    ]
