# Generated by Django 6.0.7 on 2026-07-25 01:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_restaurantinfo_is_open'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['display_order', 'customer_name']},
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('customer_name', models.CharField(blank=True, default='', max_length=120)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notification_type', models.CharField(choices=[('new_order', 'New Order'), ('status_change', 'Status Change')], default='new_order', max_length=30)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='website.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
