# Generated by Django 6.0.7 on 2026-07-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_review_options_ordernotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfeedback',
            name='avatar_file',
            field=models.FileField(blank=True, help_text='Uploaded customer photo/avatar', null=True, upload_to='avatars/'),
        ),
    ]
