# Generated by Django 6.0.7 on 2026-07-29 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_deduplicate_reviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='customerfeedback',
            name='avatar_file',
            field=models.FileField(blank=True, help_text='Uploaded customer photo/avatar', null=True, upload_to='reviews/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='about_history',
            field=models.TextField(default='Amazing Foods opened in Jamrud in 2018 to serve flavorful, high-quality fast food—from wood-fired pizzas and shawarmas to crispy zinger burgers and aromatic chicken pulao.'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='address',
            field=models.CharField(default='Amazing foods jamrud', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='email',
            field=models.EmailField(default='info@amazingfoods.pk', max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='name',
            field=models.CharField(default='Amazing Foods', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='phone',
            field=models.CharField(default='+92 323 2870355', max_length=20),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='whatsapp_number',
            field=models.CharField(default='923232870355', max_length=20),
        ),
        migrations.AlterField(
            model_name='review',
            name='avatar_file',
            field=models.FileField(blank=True, help_text='Or upload avatar image file directly', null=True, upload_to='reviews/'),
        ),
    ]
