# Generated by Django 6.0.7 on 2026-08-06 12:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0015_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantinfo',
            name='about_history',
            field=models.TextField(default='Amazing Foods opened in Peshawar in 2018 to serve flavorful, high-quality fast food—from wood-fired pizzas and shawarmas to crispy zinger burgers and aromatic chicken pulao.'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='address',
            field=models.CharField(default='Amazing Foods Peshawar', max_length=255),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='email',
            field=models.EmailField(default='mharisyar.ai@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='google_maps_plus_code',
            field=models.CharField(default='Peshawar, Pakistan', max_length=50),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_description',
            field=models.TextField(default='Experience the finest fast food in Peshawar. From wood-fired pizzas and local shawarmas to aromatic chicken pulao, we cook every deal fresh with premium ingredients.'),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(help_text='e.g. Cooking Oil, Cheese, Flour, Meat', max_length=150)),
                ('item_quantity', models.CharField(help_text='e.g. 50 kg, 20 liters, 10 cartons', max_length=100)),
                ('date_bought', models.DateField(default=django.utils.timezone.now, help_text='Date when item was purchased')),
                ('how_much_left', models.CharField(help_text='e.g. 15 kg left, 5 liters, 30%', max_length=100)),
                ('last_updated', models.DateField(default=django.utils.timezone.now, help_text='Date when inventory count was last updated')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to='website.restaurantinfo')),
            ],
            options={
                'verbose_name': 'Inventory Item',
                'verbose_name_plural': 'Inventory Items',
                'ordering': ['-date_bought', '-id'],
            },
        ),
    ]
