# Generated by Django 6.0.7 on 2026-08-12 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0016_alter_restaurantinfo_about_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation_name',
            field=models.CharField(blank=True, default='', help_text="Variation selected by the customer, e.g. 'Small', 'Medium'. Empty when no variation applies.", max_length=100),
        ),
        migrations.CreateModel(
            name='ProductVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Variation label, e.g. Small, Medium, Large, Half, Full.', max_length=100)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price for this specific variation.', max_digits=10)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Controls the order variations are listed on the menu (lowest first).')),
                ('product', models.ForeignKey(help_text='The parent product this variation belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='website.product')),
            ],
            options={
                'verbose_name': 'Product Variation',
                'verbose_name_plural': 'Product Variations',
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
