# Generated by Django 6.0.7 on 2026-08-17 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0017_add_product_variation_and_orderitem_variation_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Online Delivery'), ('dine_in', 'Dine-in')], db_index=True, default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card / POS'), ('online', 'Online Payment')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, default='', help_text='e.g. Table 5, T-12', max_length=30),
        ),
    ]
