# Generated by Django 6.0.7 on 2026-07-29 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Digits only e.g. 923232870355', max_length=30, unique=True)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('default_address', models.TextField(blank=True, default='')),
                ('state', models.CharField(choices=[('IDLE', 'Idle / Welcome'), ('MAIN_MENU', 'Browsing Categories'), ('BUILDING_ORDER', 'Building Draft Cart'), ('AWAITING_ADDRESS', 'Awaiting Delivery Address'), ('CONFIRMING_ORDER', 'Confirming Final Order')], db_index=True, default='IDLE', max_length=30)),
                ('draft_cart_data', models.JSONField(blank=True, default=list, help_text="Active cart items e.g. [{'product_id': 1, 'qty': 2}]")),
                ('selected_category_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_interaction', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Customer',
                'verbose_name_plural': 'WhatsApp Customers',
                'ordering': ['-last_interaction'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number_id', models.CharField(blank=True, default='', help_text='Meta Business Phone Number ID', max_length=100)),
                ('access_token', models.TextField(blank=True, default='', help_text='Meta Permanent Access Token')),
                ('verify_token', models.CharField(default='amazing_foods_wa_secret_2026', help_text='Webhook Verify Secret Token', max_length=100)),
                ('app_secret', models.CharField(blank=True, default='', help_text='Meta App Secret for HMAC validation', max_length=100)),
                ('auto_reply_enabled', models.BooleanField(default=True, help_text='Toggle automatic WhatsApp AI replies')),
                ('welcome_message', models.TextField(default='Welcome to Amazing Foods! 🍔\nHow can we serve you today?')),
                ('closed_hours_message', models.TextField(default='Thank you for contacting Amazing Foods! We are currently closed. Please check our opening hours.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'WhatsApp Integration Setting',
                'verbose_name_plural': 'WhatsApp Integration Settings',
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, help_text='Meta message ID for idempotency', max_length=100, unique=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (From Customer)'), ('outbound', 'Outbound (From Assistant)')], default='inbound', max_length=20)),
                ('body', models.TextField(blank=True, default='')),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='received', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappcustomer')),
            ],
            options={
                'verbose_name': 'WhatsApp Message Log',
                'verbose_name_plural': 'WhatsApp Message Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
