# Generated by Django 6.0.7 on 2026-07-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappcustomer',
            name='kitchen_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='whatsappcustomer',
            name='order_type',
            field=models.CharField(choices=[('delivery', 'Delivery 🛵'), ('pickup', 'Pickup / Takeaway 🛍️')], default='delivery', max_length=20),
        ),
        migrations.AlterField(
            model_name='whatsappcustomer',
            name='draft_cart_data',
            field=models.JSONField(blank=True, default=list, help_text="Active cart items e.g. [{'product_id': 1, 'name': 'Zinger', 'price': 450, 'qty': 2}]"),
        ),
        migrations.AlterField(
            model_name='whatsappcustomer',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle / Welcome'), ('WELCOME_BACK', 'Welcome Back (Persistent Cart)'), ('MAIN_MENU', 'Browsing Categories'), ('BUILDING_ORDER', 'Building Draft Cart'), ('EDIT_CART', 'Editing Cart'), ('SELECT_ORDER_TYPE', 'Selecting Delivery or Pickup'), ('AWAITING_ADDRESS', 'Awaiting Delivery Address'), ('AWAITING_NOTES', 'Awaiting Kitchen Notes'), ('CONFIRMING_ORDER', 'Confirming Final Order')], db_index=True, default='IDLE', max_length=30),
        ),
    ]
