# Generated by Django 6.0.7 on 2026-07-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0002_whatsappcustomer_kitchen_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappsetting',
            name='estimated_prep_time',
            field=models.CharField(default='25 - 35 mins', help_text='Estimated preparation time shown in order summary', max_length=50),
        ),
    ]
