# Generated by Django 6.0.7 on 2026-07-29 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_alter_deal_options_and_more'),
        ('whatsapp', '0003_whatsappsetting_estimated_prep_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Owner Dashboard Bell'), ('sms', 'SMS'), ('email', 'Email')], db_index=True, max_length=20)),
                ('provider', models.CharField(db_index=True, default='meta', help_text='Provider e.g. meta, dashboard, twilio, smtp', max_length=30)),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled')], db_index=True, max_length=50)),
                ('attempt_number', models.PositiveIntegerField(default=1, help_text='Delivery attempt sequence number')),
                ('recipient', models.CharField(help_text='Recipient phone number or target identifier', max_length=100)),
                ('rendered_message', models.TextField(help_text='Exact, immutable message text delivered on this attempt')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', help_text='Meta wamid or external message identifier', max_length=100)),
                ('error_message', models.TextField(blank=True, default='', help_text='Error message if attempt failed')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='website.order')),
            ],
            options={
                'verbose_name': 'Notification Delivery Attempt Log',
                'verbose_name_plural': 'Notification Delivery Attempt Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('dashboard', 'Owner Dashboard Bell'), ('sms', 'SMS'), ('email', 'Email')], db_index=True, default='whatsapp', max_length=20)),
                ('event_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_preparing', 'Order Preparing'), ('order_ready', 'Order Ready'), ('order_completed', 'Order Completed'), ('order_cancelled', 'Order Cancelled')], db_index=True, max_length=50)),
                ('body_template', models.TextField(help_text='Template text with placeholders like {customer_name}, {order_id}, {total}, {prep_time}')),
                ('version', models.PositiveIntegerField(default=1, help_text='Template version number for audit tracking')),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['channel', 'event_type', '-version'],
                'constraints': [models.UniqueConstraint(fields=('channel', 'event_type', 'version'), name='unique_template_version_per_channel_event')],
            },
        ),
    ]
