# Generated by Django 6.0.7 on 2026-07-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp', '0004_notificationlog_notificationtemplate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='whatsappcustomer',
            name='order_type',
        ),
        migrations.AlterField(
            model_name='whatsappcustomer',
            name='state',
            field=models.CharField(choices=[('IDLE', 'Idle / Welcome'), ('WELCOME_BACK', 'Welcome Back (Persistent Cart)'), ('MAIN_MENU', 'Browsing Categories'), ('BUILDING_ORDER', 'Building Draft Cart'), ('EDIT_CART', 'Editing Cart'), ('AWAITING_ADDRESS', 'Awaiting Delivery Address'), ('AWAITING_NOTES', 'Awaiting Kitchen Notes'), ('CONFIRMING_ORDER', 'Confirming Final Order')], db_index=True, default='IDLE', max_length=30),
        ),
    ]
